# Generated by Django 6.0.1 on 2026-08-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('b2b', 'business to business'), ('on-commission', 'on commission'), ('no-interest', 'no interest')], default='pending', max_length=20),
        ),
    ]
