# Generated by Django 6.0.1 on 2026-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_storetype_store_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
