# Generated by Django 6.0.1 on 2026-09-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_store_city_store_postal_code_store_street_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
    ]
